"""fix relation between playergameinfo and game

Revision ID: 8b2a35caa5db
Revises: 1d57d3244b6d
Create Date: 2024-07-04 20:23:04.664893

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b2a35caa5db'
down_revision: Union[str, None] = '1d57d3244b6d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'game', ['id'])
    op.create_unique_constraint(None, 'player', ['id'])
    op.add_column('player_game_info', sa.Column('game_id', sa.Integer(), nullable=False))
    op.create_unique_constraint(None, 'player_game_info', ['id'])
    op.create_foreign_key(None, 'player_game_info', 'game', ['game_id'], ['id'])
    op.create_unique_constraint(None, 'template', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'template', type_='unique')
    op.drop_constraint(None, 'player_game_info', type_='foreignkey')
    op.drop_constraint(None, 'player_game_info', type_='unique')
    op.drop_column('player_game_info', 'game_id')
    op.drop_constraint(None, 'player', type_='unique')
    op.drop_constraint(None, 'game', type_='unique')
    # ### end Alembic commands ###
