"""add next tables

Revision ID: 1d57d3244b6d
Revises: 92647dda129e
Create Date: 2024-07-03 19:29:14.172366

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d57d3244b6d'
down_revision: Union[str, None] = '92647dda129e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('template',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('game',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('game_result', sa.Integer(), nullable=False),
    sa.Column('restarts', sa.Integer(), nullable=False),
    sa.Column('start_datetime', sa.DateTime(), nullable=False),
    sa.Column('end_datetime', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['template.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('player_game_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('color', sa.Integer(), nullable=False),
    sa.Column('town', sa.Integer(), nullable=False),
    sa.Column('hero', sa.Integer(), nullable=False),
    sa.Column('color2', sa.Integer(), nullable=False),
    sa.Column('town2', sa.Integer(), nullable=False),
    sa.Column('hero2', sa.Integer(), nullable=False),
    sa.Column('rating_before', sa.Integer(), nullable=False),
    sa.Column('rating_after', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['player.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('player_game_info')
    op.drop_table('game')
    op.drop_table('template')
    # ### end Alembic commands ###
