"""switch to sqlmodel

Revision ID: b0ddf1c8f6a9
Revises: 8b2a35caa5db
Create Date: 2024-07-04 22:34:39.336665

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0ddf1c8f6a9'
down_revision: Union[str, None] = '8b2a35caa5db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
