"""drop raw column

Revision ID: e3fafc74bd6e
Revises: b0ddf1c8f6a9
Create Date: 2024-07-07 23:27:44.896707

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e3fafc74bd6e'
down_revision: Union[str, None] = 'b0ddf1c8f6a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('player', 'raw')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player', sa.Column('raw', postgresql.BYTEA(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
